package com.growwithcode.auth;
import com.growwithcode.user.*;import jakarta.validation.Valid;import java.time.Instant;import java.time.temporal.ChronoUnit;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.HttpStatus;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.security.oauth2.jose.jws.MacAlgorithm;import org.springframework.security.oauth2.jwt.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;
@RestController @RequestMapping("/api/auth") public class AuthController{
private final UserRepository users;private final PasswordEncoder passwords;private final JwtEncoder jwt;private final String issuer;
AuthController(UserRepository u,PasswordEncoder p,JwtEncoder j,@Value("${app.jwt-issuer}")String i){users=u;passwords=p;jwt=j;issuer=i;}
@PostMapping("/register") @ResponseStatus(HttpStatus.CREATED) AuthResponse register(@Valid @RequestBody RegisterRequest r){String e=r.email().trim().toLowerCase();if(users.existsByEmailIgnoreCase(e))throw new ResponseStatusException(HttpStatus.CONFLICT,"Email already registered");var u=users.save(new User(e,passwords.encode(r.password()),r.displayName().trim()));return issue(u);}
@PostMapping("/login") AuthResponse login(@Valid @RequestBody LoginRequest r){var u=users.findByEmailIgnoreCase(r.email().trim()).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid credentials"));if(!passwords.matches(r.password(),u.getPasswordHash()))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid credentials");return issue(u);}
private AuthResponse issue(User u){Instant now=Instant.now();var claims=JwtClaimsSet.builder().issuer(issuer).issuedAt(now).expiresAt(now.plus(2,ChronoUnit.HOURS)).subject(u.getId().toString()).claim("email",u.getEmail()).claim("name",u.getDisplayName()).build();String t=jwt.encode(JwtEncoderParameters.from(JwsHeader.with(MacAlgorithm.HS256).build(),claims)).getTokenValue();return new AuthResponse(t,new UserView(u.getId(),u.getEmail(),u.getDisplayName()));}
}
